### ISSUE TITLE
yaza: ORG directive

### ISSUE THREAD

**Issue by depili** [toptensoftware/yazd#1]
I'm doing reverse engineering on a VPS-300P video production system controller, which uses z80 compatible processors: https://github.com/depili/vps-300p

Now when I'm in the "oh, we should now know all we need to know, let's write the new code" -phase I ran into an issue with yaza and the ORG directive. I am trying to place the interrupt vector table on a known location with the ORG directive as ideally I would like to keep it in the same place as in the original rom.

If I add ORG 0x0070 directive to https://github.com/depili/vps-300p/commit/260b913d76d71bb44c1e90bc14ca824a23a3a503#diff-b4a9c61ae905ee6c6f7e51f13833d6f4R33 and then assemble and dissassemble with --entry:0 I see that the jump to the main loop gets messed up. Without the org directive assembling and then dissassembling results in expected code flow.

**Comment by depili** [comment]
Got the placement working by using SEEK and ORG both: https://github.com/depili/vps-300p/commit/f0591d04ca7b6813747e204ca985d93625ba2844

**Comment by toptensoftware** [comment]
Yep, thats the correct way of doing this.  Org only repositions the assemblers concept of the address of the following instructions - it doesn't change where the instructions are generated to.
