### ISSUE TITLE
YAZD should not stop disassemblng after a RST

### ISSUE THREAD

**Issue by theNestruo** [toptensoftware/yazd#10]
When YAZD finds a RST instruction, the routine is considered finished. For example:
```
        ; (...)
        pop     hl
        ld      a,$20           ; ' '
        rst     0x10

L00C1:  DB      $EB
        DB      $E1
        DB      $23             ; '#'
        ; (...)
```
But RST is a shorthand for a CALL, and the routine actually continues after the RST, as can be seen with an additional entry point:
```
        ; (...)
        pop     hl
        ld      a,$20           ; ' '
        rst     0x10

        ; Entry Point
        ; --- START PROC L00C1 ---
L00C1:  ex      de,hl
        pop     hl
        inc     hl
        ; (...)
```
I guess this behaviour can be changed in `yazd/OpCodes.cs` by replacing the `OpCodeFlags` of the RST `OpCodes` with `OpCodeFlags.Restarts | OpCodeFlags.Continues` (currently they are: `OpCodeFlags.Restarts`).

Note: for reference purposes, the routine at $0010 is:
```
L0010:  add     a,l
        ld      l,a
        ret     nc
        inc     h
        ret
```

**Comment by toptensoftware** [comment]
Thank you.  Fixed.

**Comment by theNestruo** [comment]
Thank you very much!
It would be a nice addition to "START PROC" (and "Referenced from") at RST destinations (0x10, 0x18, etc.) if those address are present in the disassembly (they are detected as data). But meanwhile some additional entry points (`--entry:0x0010`, etc.) can do the trick!
