### ISSUE TITLE
Crash while disassembling CP/M Plus BDOS/BIOS (S10CPM3.EMS)

### ISSUE THREAD

**Issue by mistificator** [toptensoftware/yazd#11]
.\yazd.exe .\p3explorer\cpm3\S10CPM3.EMS S10CPM3.ASM

Необработанное исключение: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в yazd.CallGraphAnalyzer.AnalyseProc(Proc p, List`1 procList)
   в yazd.CallGraphAnalyzer.Analyse()
   в yazd.Program.Run(String[] args)
   в yazd.Program.Main(String[] args)

It's "Unhandled exception" message. Sorry for Russian language.
Output file has zero size.

**Comment by toptensoftware** [comment]
Can you [send me](http://www.toptensoftware.com/contact) a copy of the file or a link to where I can download the exact one you're having issues with.

**Comment by mistificator** [comment]
https://www.planetemu.net/rom/sinclair-zx-spectrum-dsk/cp-m-plus-v1-0-19xx-locomotive-software-side-1

**Comment by toptensoftware** [comment]
That looks like a disk image... I'll need the actual file you're trying to disassemble.

**Comment by mistificator** [comment]
Okay, I'll extract it later. The file is from this image.
Or you could extract file by yourself with freeware programs CPCDiskXP or P3Explorer.

**Comment by mistificator** [comment]
[S10CPM3.zip](https://github.com/toptensoftware/yazd/files/3917685/S10CPM3.zip)

**Comment by toptensoftware** [comment]
Thanks.  Fixed.

**Comment by mistificator** [comment]
Wow! Thank you. I'll try it soon.
