### ISSUE TITLE
YAZA shows error at ld with math expression

### ISSUE THREAD

**Issue by mistificator** [toptensoftware/yazd#12]
`ld b, (RAM_Switch_Map_End  - RAM_Switch_Map) / RAM_Switch_Map_Line`
generates
```
.\test.asm(379,50): syntax error: expected end of line, found '/'
.\test.asm(379,5): invalid addressing mode: ld b,(?)
Errors: 2 Warnings: 0
```

If I change it to 
`ld b, RAM_Switch_Map_End / RAM_Switch_Map_Line  - RAM_Switch_Map / RAM_Switch_Map_Line `
error disappears
`Errors: 0 Warnings: 0`

I think `(RAM_Switch_Map_End  - RAM_Switch_Map) / RAM_Switch_Map_Line` is legal expression in this case and should be interpreted as math expression.

**Comment by toptensoftware** [comment]
This is by design.  [See here](https://github.com/toptensoftware/yazd/blob/master/yaza.md#expressions) the note about parentheses.

**Comment by mistificator** [comment]
`0+(RAM_Switch_Map_End - RAM_Switch_Map) / RAM_Switch_Map_Line`
okay
