### ISSUE TITLE
yaza: labels "end:" or "error:" cause problems

### ISSUE THREAD

**Issue by depili** [toptensoftware/yazd#2]
For some reason if I use labels "end:" or "error:" inside procs the yaza fails on assembling the code. An example of a failing code:

```
MAIN: PROC
		LD A, 0x00
end:	LD A, 0x00
error:	LD A, 0x00
ENDP
```

**Comment by toptensoftware** [comment]
That's because `end` and `error` are both reserved words. 

See [here](https://github.com/toptensoftware/yazd/blob/master/yaza.md#the-defined-operator) for example of `end if`

and [here](https://github.com/toptensoftware/yazd/blob/master/yaza.md#the-defined-operator) for example of `error`
