### ISSUE TITLE
YAZA: labels in macros are not local

### ISSUE THREAD

**Issue by depili** [toptensoftware/yazd#3]
I was trying to use the following macro with a label. Assembling the code with multiple calls to that macro did not produce any errors or warning, but ´JR Z,send´ jumps ended up pointing to the last macro invocation. A fix was to use $+0x04 instead of the label.
```
KB_BIT(chk_bit) MACRO
	LD	E, 0 + (chk_bit << 3)		; Bit code
	BIT	chk_bit, B
	JR	Z, send
	SET	6, E
send:
	CALL	KEYB_SEND
	RES	chk_bit, A
	JP	KEYB_BYTE_DIFF
ENDM
```

**Comment by toptensoftware** [comment]
Fixed in latest build
