### ISSUE TITLE
YAZD can't disassemble file ending at FFFFh

### ISSUE THREAD

**Issue by nippur72** [toptensoftware/yazd#5]
I have a .BIN file from D000h to FFFFh, when runnung yazd it tells me "out of range". I had to trim one byte at the end of the file to make it work. 

```
$ yazd --addr:0xD000 roms\D000FFFF.BIN
Address 0xD000 is out of range 0xD000-0x0000
```

**Comment by toptensoftware** [comment]
Fixed in latest
