### ISSUE TITLE
YAZD literal constants format

### ISSUE THREAD

**Issue by nippur72** [toptensoftware/yazd#6]
can we have a switch for selecting the format of literal constants, e.g. `$A0` vs `0A0h` ?

**Comment by toptensoftware** [comment]
Why do you need a switch?  Both formats are already supported - [see here](https://github.com/toptensoftware/yazd/blob/master/yaza.md#numeric-literals).

**Comment by nippur72** [comment]
in YAZE yes, but how to make YAZD produce such literals?

**Comment by toptensoftware** [comment]
Ah ok.  Sorry I misunderstood. Can probably add that.

**Comment by toptensoftware** [comment]
Available in latest build.

    --hex:<format>         Specify hex literal formatting (options: $, dollar, &, amper, x or h)

eg: 

* `--hex:dollar` = `$FF`
* `--hex:amper` = `&hFF`
* `--hex:x` = `0xFF`
* `--hex:h` = `0FFh`

**Comment by nippur72** [comment]
thanks a lot! Nice assembler/disassembler, I'm using it in place of `z88asm` and `z88dk-dis` 👍
